### ISSUE TITLE
PYTHONPATH variable error

### ISSUE THREAD

**Issue by Ni-vik** [NASA-IMPACT/hls-foundation-os#23]
I cloned his repository and followed all the steps given in readme file. After running 
mim train mmsegmentation --launcher pytorch configs/burn_scars.py 

I am getting the following error

You should set `PYTHONPATH` to make `sys.path` include the directory which contains your custom module.

I tried setting PYTHONPATH variable. But even after updating the environment variable it is shwoing the same error

**Comment by JulsdL** [comment]
The mim command changes the os type to a <class 'mmengine.config.lazy.LazyObject'>, and the path management turns crazy. I've been trying to make it work for the last 24h.

**Comment by CarlosGomes98** [comment]
Hi @Ni-vik and @JulsdL . I am trying to replicate the error, but am not being able to.

Could I ask for the full log output you obtain, as well as where you are running the command from?

Could I also ask for the output of pip list from the environment you are using?

**Comment by Ni-vik** [comment]
Thank you @CarlosGomes98 . 
I am running this locally using VS code and on cpu devive.

I tried installing it again. So at first when I ran 
`pip install -e .`

This gives an error related to long file names (I accidently killed terminal I am finding way to get the logs so that I can share the log). I was able to resolve that from <a href = "https://stackoverflow.com/questions/52699177/how-to-fix-filename-too-long-error-during-git-clone">here</a>

After doing that the longfilename error was resolved but there was one more error related to proxy. I resolved it from <a href = "https://stackoverflow.com/questions/18356502/github-failed-to-connect-to-github-443-windows-failed-to-connect-to-github"> here </a>

After running : 

`mim train mmsegmentation --launcher pytorch configs/burn_scars.py`

Now I am having issue related to mmcv.


ImportError: DLL load failed while importing _ext: The specified procedure could not be found.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 22972) of binary: C:\Users\NISHANT\anaconda3\envs\nasa_issue\python.exe

My pip list:

Package                 Version      Editable project location
----------------------- ------------ ----------------------------------
absl-py                 2.0.0
addict                  2.4.0
affine                  2.4.0
aliyun-python-sdk-core  2.14.0
aliyun-python-sdk-kms   2.16.2
attrs                   23.1.0
cachetools              5.3.1
certifi                 2023.7.22
cffi                    1.16.0
charset-normalizer      3.3.0
click                   8.1.7
click-plugins           1.1.1
cligj                   0.7.2
colorama                0.4.6
contourpy               1.1.1
crcmod                  1.7
cryptography            41.0.4
cycler                  0.12.1
einops                  0.7.0
fonttools               4.43.1
geospatial-fm           0.1.0        c:\users\nishant\hls-foundation-os
google-auth             2.23.2
google-auth-oauthlib    1.0.0
grpcio                  1.59.0
idna                    3.4
imagecodecs             2023.9.18
importlib-metadata      6.8.0
importlib-resources     6.1.0
jmespath                0.10.0
kiwisolver              1.4.5
Markdown                3.5
markdown-it-py          3.0.0
MarkupSafe              2.1.3
matplotlib              3.8.0
mdurl                   0.1.2
mkl-fft                 1.3.8
mkl-random              1.2.4
mkl-service             2.4.0
mmcls                   0.25.0
mmcv-full               1.6.2
mmsegmentation          0.30.0
model-index             0.1.11
numpy                   1.26.0
oauthlib                3.2.2
opencv-python           4.8.1.78
opendatalab             0.0.10
openmim                 0.3.9
openxlab                0.0.26
ordered-set             4.1.0
oss2                    2.17.0
packaging               23.2
pandas                  2.1.1
Pillow                  10.0.1
pip                     23.2.1
platformdirs            3.11.0
prettytable             3.9.0
protobuf                4.24.4
pyasn1                  0.5.0
pyasn1-modules          0.3.0
pycparser               2.21
pycryptodome            3.19.0
Pygments                2.16.1
pyparsing               3.1.1
python-dateutil         2.8.2
pytz                    2023.3.post1
pywin32                 306
PyYAML                  6.0.1
rasterio                1.3.8
regex                   2023.10.3
requests                2.28.2
requests-oauthlib       1.3.1
rich                    13.4.2
rsa                     4.9
setuptools              60.2.0
six                     1.16.0
snuggs                  1.4.7
tabulate                0.9.0
tensorboard             2.14.1
tensorboard-data-server 0.7.1
tifffile                2023.9.26
timm                    0.4.12
tomli                   2.0.1
torch                   1.10.1
torchaudio              0.10.1
torchvision             0.11.2
tqdm                    4.65.2
typing_extensions       4.7.1
tzdata                  2023.3
urllib3                 1.26.17
wcwidth                 0.2.8
Werkzeug                3.0.0
wheel                   0.41.2
yapf                    0.40.2
zipp                    3.17.0

Here is the complete log
Using port 28701 for synchronization. 
Training command is C:\Users\NISHANT\anaconda3\envs\nasa_issue\python.exe -m torch.distributed.launch --nproc_per_node=1 --master_port=28701 c:\users\nishant\anaconda3\envs\nasa_issue\lib\site-packages\mmseg\.mim\tools\train.py configs/burn_scars.py --launcher pytorch.
NOTE: Redirects are currently not supported in Windows or MacOs.
C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\site-packages\torch\distributed\launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\site-packages\mmcv\cnn\bricks\transformer.py:33: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module.
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
Traceback (most recent call last):
  File "c:\users\nishant\anaconda3\envs\nasa_issue\lib\site-packages\mmseg\.mim\tools\train.py", line 17, in <module>
    from mmseg.apis import init_random_seed, set_random_seed, train_segmentor
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\site-packages\mmseg\apis\__init__.py", line 2, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\site-packages\mmseg\apis\inference.py", line 9, in <module>
    from mmseg.models import build_segmentor
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\site-packages\mmseg\models\__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\site-packages\mmseg\models\backbones\__init__.py", line 7, in <module>
    from .fast_scnn import FastSCNN
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\site-packages\mmseg\models\backbones\fast_scnn.py", line 7, in <module>
    from mmseg.models.decode_heads.psp_head import PPM
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\site-packages\mmseg\models\decode_heads\__init__.py", line 2, in <module>
    from .ann_head import ANNHead
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\site-packages\mmseg\models\decode_heads\ann_head.py", line 8, in <module>
    from .decode_head import BaseDecodeHead
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\site-packages\mmseg\models\decode_heads\decode_head.py", line 12, in <module>
    from ..losses import accuracy
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\site-packages\mmseg\models\losses\__init__.py", line 6, in <module>
    from .focal_loss import FocalLoss
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\site-packages\mmseg\models\losses\focal_loss.py", line 6, in <module>
    from mmcv.ops import sigmoid_focal_loss as _sigmoid_focal_loss
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: The specified procedure could not be found.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 22972) of binary: C:\Users\NISHANT\anaconda3\envs\nasa_issue\python.exe
Traceback (most recent call last):
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\site-packages\torch\distributed\launch.py", line 193, in <module>
    main()
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\site-packages\torch\distributed\launch.py", line 189, in main
    launch(args)
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\site-packages\torch\distributed\launch.py", line 174, in launch
    run(args)
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\site-packages\torch\distributed\run.py", line 710, in run
    elastic_launch(
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\site-packages\torch\distributed\launcher\api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\site-packages\torch\distributed\launcher\api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
c:\users\nishant\anaconda3\envs\nasa_issue\lib\site-packages\mmseg\.mim\tools\train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-10-08_09:17:34
  host      : LAPTOP-EOAH8V2A.mitwpu.edu.in
============================================================
Traceback (most recent call last):
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\Scripts\mim.exe\__main__.py", line 7, in <module>
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\site-packages\mim\commands\train.py", line 100, in cli
    is_success, msg = train(
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\site-packages\mim\commands\train.py", line 261, in train
    ret = subprocess.check_call(
  File "C:\Users\NISHANT\anaconda3\envs\nasa_issue\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\NISHANT\\anaconda3\\envs\\nasa_issue\\python.exe', '-m', 'torch.distributed.launch', '--nproc_per_node=1', '--master_port=28701', 'c:\\users\\nishant\\anaconda3\\envs\\nasa_issue\\lib\\site-packages\\mmseg\\.mim\\tools\\train.py', 'configs/burn_scars.py', '--launcher', 'pytorch']' returned non-zero exit status 1.
(nasa_issue) PS C:\Users\NISHANT\hls-foundation-os>

**Comment by Ni-vik** [comment]
Thank you @CarlosGomes98 . 
I am running it locally using VS code terminal and CPU device.

I tried installing it again by creating a new environment.
After running 'pip install -e .'
There were 2 errors (I don't have the complete log though I killed the terminal accidently. I am finding a way to restore the history)

One was related to longfile names. I resolved it from <a href = "https://stackoverflow.com/questions/52699177/how-to-fix-filename-too-long-error-during-git-clone">here</a>

Other one was failed to connect to github. Fixed it from <a href = "https://stackoverflow.com/questions/18356502/github-failed-to-connect-to-github-443-windows-failed-to-connect-to-github"> here</a>

Now after running 
`mim train mmsegmentation --launcher pytorch configs/burn_scars.py`
I am getting errors. Here is the complete log

![1](https://github.com/NASA-IMPACT/hls-foundation-os/assets/90412779/75c73f10-cbb4-44c1-935b-41d873a7adb4)
![2](https://github.com/NASA-IMPACT/hls-foundation-os/assets/90412779/17935133-f18b-4b2c-aa22-288cccbe2ab0)
![3](https://github.com/NASA-IMPACT/hls-foundation-os/assets/90412779/d5d199f4-65b2-4f01-9d4d-88a73ae0e739)
![4](https://github.com/NASA-IMPACT/hls-foundation-os/assets/90412779/22bc81a4-f360-4f79-a9da-9a9b6f545536)

Here is my pip list

![p1](https://github.com/NASA-IMPACT/hls-foundation-os/assets/90412779/7f5fa09c-9629-4d46-b0ff-8a91b35f5586)
![p2](https://github.com/NASA-IMPACT/hls-foundation-os/assets/90412779/3f340b0a-0fd1-4d0f-9dce-cf82df873570)
![p3](https://github.com/NASA-IMPACT/hls-foundation-os/assets/90412779/b6b0bba9-749c-4929-a5cc-b3a93cf08a2f)

**Comment by CarlosGomes98** [comment]
It seems you are running this on windows. I would suggest trying it from windows subsystem for Linux. https://learn.microsoft.com/en-us/windows/wsl/install Windows tends to make things a bit messier with these libraries...

I'd also ask you to check if you correctly installed `mmcv-full` as per the README, and not `mmcv`.

**Comment by Ni-vik** [comment]
I will try to run it using windows subsystem.

I installed mmcv according to readme and also checked if it is compatible with torch version and cpu device. 

![torch](https://github.com/NASA-IMPACT/hls-foundation-os/assets/90412779/a9457bb4-9676-4be2-a065-44f814c7e063)
![mmcv](https://github.com/NASA-IMPACT/hls-foundation-os/assets/90412779/14aa7fcf-9481-4b78-8af3-abf958642fc6)

**Comment by JulsdL** [comment]
Is there any prerequisites we should be aware of before following the setup instructions ?
Like, do we need Nvidia CUDA and cuDNN library installed ? Or anything like that ?

**Comment by Ni-vik** [comment]
> Is there any prerequisites we should be aware of before following the setup instructions ?
> Like, do we need Nvidia CUDA and cuDNN library installed ? Or anything like that ?

If you want to run it on CPU then I don’t think so you need those. But in case of GPUs you might need those installed. @CarlosGomes98 will know better about it.

**Comment by CarlosGomes98** [comment]
For running on CPU, it is sufficient to install the CPU version of torch and the matching version of mmcv-full.

For running on GPU, you should have the appropriate drivers installed. The torch install should then pull all the necessary CUDNN and CUDA libraries.
