### ISSUE TITLE
 ModuleNotFoundError: No module named 'geospatial_fm' Fine-Tuning

### ISSUE THREAD

**Issue by Roopesh-Bharatwaj-K-R** [NASA-IMPACT/hls-foundation-os#26]
Hi, 

After the  update of Readme file, I followed the Fine-tuning steps and I could not proceed further as there was a blockage in the config file -> [sen1floods11_config.py]

> In the configs folder there are three config examples for the three segmentation tasks. Complete the configs with your setup specifications. Parts that must be completed are marked with #TO BE DEFINED BY USER. They relate to the location where you downloaded the dataset, pretrained model weights, the test set (e.g. regular one or Bolivia out-of-bag data) and where you are going to save the experiment outputs. |

```Training command is /usr/bin/python3 /usr/local/lib/python3.10/dist-packages/mmseg/.mim/tools/train.py

/content/drive/MyDrive/Prithvi_Fine-Tuning/hls-foundation-os/configs/sen1floods11_config.py --launcher none. 

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/mmengine/utils/misc.py", line 77, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked

ModuleNotFoundError: No module named 'geospatial_fm'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/mmengine/config/config.py", line 462, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "/usr/local/lib/python3.10/dist-packages/mmengine/utils/misc.py", line 84, in import_modules_from_strings
    raise ImportError(f'Failed to import {imp}')
ImportError: Failed to import geospatial_fm

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/mmseg/.mim/tools/train.py", line 104, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/mmseg/.mim/tools/train.py", line 58, in main
    cfg = Config.fromfile(args.config)
  File "/usr/local/lib/python3.10/dist-packages/mmengine/config/config.py", line 474, in fromfile
    raise ImportError(err_msg) from e
ImportError: Failed to import custom modules from {'imports': ['geospatial_fm']}, the current sys.path is: 
    /usr/local/lib/python3.10/dist-packages/mmseg/.mim/tools
    /env/python
    /usr/lib/python310.zip
    /usr/lib/python3.10
    /usr/lib/python3.10/lib-dynload
    /usr/local/lib/python3.10/dist-packages
    /usr/lib/python3/dist-packages

You should set `PYTHONPATH` to make `sys.path` include the directory which contains your custom module
Traceback (most recent call last):

  File "/usr/local/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mim/commands/train.py", line 100, in cli
    is_success, msg = train(
  File "/usr/local/lib/python3.10/dist-packages/mim/commands/train.py", line 261, in train
    ret = subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/usr/local/lib/python3.10/dist-packages/mmseg/.mim/tools/train.py', '/content/drive/MyDrive/Prithvi_Fine-Tuning/hls-foundation-os/configs/sen1floods11_config.py', '--launcher', 'none']' returned non-zero exit status 1.`
```

Any Help on how can we sort this out, As we are doing a Custom Fine Tuning  Model?

Best Regards,
Roopesh Bharatwaj K R

**Comment by Ni-vik** [comment]
Check issue #23. I was having the same error.

**Comment by Roopesh-Bharatwaj-K-R** [comment]
Thanks. For it -i'm jus visiting it

**Comment by anumerico** [comment]
I was getting that at some point, the issue was that hadn't run this command within the hls-foundation-os directory:
pip install -e .
