### ISSUE TITLE
"IndexError: too many indices for tensor of dimension 2" when finetuning "mim train mmsegmentation configs/multi_temporal_crop_classification.py"

### ISSUE THREAD

**Issue by mahrokh3409** [NASA-IMPACT/hls-foundation-os#41]
Dear Community,

I followed the instructions in GitHub to run the fine-tuning for multi_temporal_crop_classification.

I edited "multi_temporal_crop_classification.py " file as follows:
- pretrained_weights_path = '**~/Downloads/IBM_weights/Prithvi_100M.pt**'     // not sure if I should use this model
- data_root = '~/multi-temporal-crop-classification'      // I cloned to multi-temporal-crop-classification repository 
- splits = dict(
    train='~/hls-foundation-os/data_splits/multi_temporal_crop_classification/training_data.txt',
    val= '~/hls-foundation-os/data_splits/multi_temporal_crop_classification/validation_data.txt',
    #test=  '<path to test split>'  /not sure where I can get the test one
)

Then I run the below command to run finetune:
~/hls-foundation-os$ **mim train mmsegmentation configs/multi_temporal_crop_classification.py**

it started fine-tuning, but I got below error
[                                                  ] 0/771, elapsed: 0s, ETA:Traceback (most recent call last):
  File "~/anaconda3/envs/Mah_IBM/lib/python3.9/site-packages/mmseg/.mim/tools/train.py", line 242, in <module>
    main()
  File "~/anaconda3/envs/Mah_IBM/lib/python3.9/site-packages/mmseg/.mim/tools/train.py", line 231, in main
    train_segmentor(
  File "~/anaconda3/envs/Mah_IBM/lib/python3.9/site-packages/mmseg/apis/train.py", line 194, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "~/anaconda3/envs/Mah_IBM/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "~/anaconda3/envs/Mah_IBM/lib/python3.9/site-packages/mmcv/runner/epoch_based_runner.py", line 58, in train
    self.call_hook('after_train_epoch')
  File "~/anaconda3/envs/Mah_IBM/lib/python3.9/site-packages/mmcv/runner/base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "~/anaconda3/envs/Mah_IBM/lib/python3.9/site-packages/mmcv/runner/hooks/evaluation.py", line 271, in after_train_epoch
    self._do_evaluate(runner)
  File "~/anaconda3/envs/Mah_IBM/lib/python3.9/site-packages/mmseg/core/evaluation/eval_hooks.py", line 51, in _do_evaluate
    results = single_gpu_test(
  File "~/anaconda3/envs/Mah_IBM/lib/python3.9/site-packages/mmseg/apis/test.py", line 128, in single_gpu_test
    result = dataset.pre_eval(result, indices=batch_indices)
  File "~7/anaconda3/envs/Mah_IBM/lib/python3.9/site-packages/mmseg/datasets/custom.py", line 300, in pre_eval
    intersect_and_union(
  File "~/anaconda3/envs/Mah_IBM/lib/python3.9/site-packages/mmseg/core/evaluation/metrics.py", line 76, in intersect_and_union
    pred_label = pred_label[mask]
**IndexError: too many indices for tensor of dimension 2**
Traceback (most recent call last):
  File "~/anaconda3/envs/Mah_IBM/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "~/anaconda3/envs/Mah_IBM/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "~/anaconda3/envs/Mah_IBM/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "~/anaconda3/envs/Mah_IBM/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "~/anaconda3/envs/Mah_IBM/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/anaconda3/envs/Mah_IBM/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "~/anaconda3/envs/Mah_IBM/lib/python3.9/site-packages/mim/commands/train.py", line 100, in cli
    is_success, msg = train(
  File "~/anaconda3/envs/Mah_IBM/lib/python3.9/site-packages/mim/commands/train.py", line 261, in train
    ret = subprocess.check_call(
  File "~/anaconda3/envs/Mah_IBM/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['~7/anaconda3/envs/Mah_IBM/bin/python', '~/anaconda3/envs/Mah_IBM/lib/python3.9/site-packages/mmseg/.mim/tools/train.py', 'configs/multi_temporal_crop_classification.py', '--launcher', 'none', '--gpus', '1']' returned non-zero exit status 1.

I do appreciate your help.

Kind Regards,
Mahrokh

**Comment by mahrokh3409** [comment]
Hi Hanxli,
Thank you for providing links. My main issue is "IndexError: too many indices for tensor of dimension 2" and not sure how to fix it.

**Comment by hanxLi** [comment]
Hello Mahrokh, we have talked to the team, and they are actively working on this right now. I think it is some new issue introduced with the various updates to the model. The initial release works just fine. Also, for the test splits, we use the same one with the validation.

**Comment by mahrokh3409** [comment]
Hi HanxLi, Thank you so much for the update. Please let me know once the issue has fixed, then I can give it a try.

**Comment by CarlosGomes98** [comment]
@mahrokh3409 thanks for raising this. Closing this and linking to #42
