### ISSUE TITLE
burn_scars.py fails with IndexError: too many indices for tensor of dimension 2

### ISSUE THREAD

**Issue by robmarkcole** [NASA-IMPACT/hls-foundation-os#44]
Run with ` mim train mmsegmentation configs/burn_scars.py` and updated paths for dataset etc. 
Training appears to be progressing well: 

<img width="822" alt="image" src="https://github.com/NASA-IMPACT/hls-foundation-os/assets/11855322/7c991a8f-fda4-4568-9c30-67f3c9ee6218">

Then: 
```
2023-12-12 13:38:44,264 - mmseg - INFO - Exp name: burn_scars.py
2023-12-12 13:38:44,265 - mmseg - INFO - Iter [1000/10000]      lr: 7.793e-06, eta: 0:57:14, time: 0.360, data_time: 0.002, memory: 10477, decode.loss_dice: 0.1742, decode.acc_seg: 93.4879, aux.loss_dice: 0.1611, aux.acc_seg: 93.6317, loss: 0.3354
[                                                  ] 0/264, elapsed: 0s, ETA:Traceback (most recent call last):
  File "/system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages/mmseg/.mim/tools/train.py", line 242, in <module>
    main()
  File "/system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages/mmseg/.mim/tools/train.py", line 231, in main
    train_segmentor(
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/mmseg/apis/train.py", line 194, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/mmcv/runner/iter_based_runner.py", line 144, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/mmcv/runner/iter_based_runner.py", line 70, in train
    self.call_hook('after_train_iter')
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/mmcv/runner/base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/mmcv/runner/hooks/evaluation.py", line 266, in after_train_iter
    self._do_evaluate(runner)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/mmseg/core/evaluation/eval_hooks.py", line 51, in _do_evaluate
    results = single_gpu_test(
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/mmseg/apis/test.py", line 128, in single_gpu_test
    result = dataset.pre_eval(result, indices=batch_indices)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/mmseg/datasets/custom.py", line 300, in pre_eval
    intersect_and_union(
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/mmseg/core/evaluation/metrics.py", line 76, in intersect_and_union
    pred_label = pred_label[mask]
IndexError: too many indices for tensor of dimension 2
Traceback (most recent call last):
  File "/home/zeus/miniconda3/envs/cloudspace/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/mim/commands/train.py", line 100, in cli
    is_success, msg = train(
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/mim/commands/train.py", line 261, in train
    ret = subprocess.check_call(
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/zeus/miniconda3/envs/cloudspace/bin/python', '/system/conda/miniconda3/envs/cloudspace/lib/python3.10/site-packages/mmseg/.mim/tools/train.py', 'configs/burn_scars.py', '--launcher', 'none', '--gpus', '1']' returned non-zero exit status 1.
```

**Comment by CarlosGomes98** [comment]
Hi @robmarkcole,

We released a fix for this earlier today. Could you try to pull the new code and see if it works?

**Comment by robmarkcole** [comment]
@CarlosGomes98 pulled in an no issues now, thanks!
